apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: payments
spec:
  paused: false
  service:
    type: LoadBalancer
  users:
    - name: paymentuser
      databases:
         - paymentsdb
         - accountsdb
  image: registry.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.4-0
  openshift: false
  port: 5432
  postgresVersion: 14
  instances:
    - name: 'pgc'
      replicas: 1
      resources:
        limits:
          cpu: 1.0
          memory: 1Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

  backups:
    pgbackrest:
      image: registry.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-0
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi

  monitoring:
    pgmonitor:
      exporter:
        image: registry.crunchydata.com/crunchydata/crunchy-postgres-exporter:ubi8-5.2.0-0

  proxy:
    pgBouncer: 
      image: registry.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-2
      config:
        global:
          admin_users: _crunchypgbouncer
          stats_users: _crunchypgbouncer
          default_pool_size: "10"
          pool_mode: session
      # service:
      #   type: LoadBalancer
      #   files:
      #     - configMap:
      #         name: acctdev-pgbouncer-custom

  patroni:
    switchover:
      enabled: true
      # targetInstance: xxxx
      type: Switchover
    dynamicConfiguration:
      postgresql:
        parameters:
          archive_timeout:  300
          checkpoint_timeout: 1200
          log_checkpoints: on
          log_connections: on
          log_disconnections: on
          log_lock_waits: on
          log_temp_files: 0
          log_autovacuum_min_duration: 0
          log_error_verbosity: default
          log_min_duration_statement: 5000
          log_rotation_size: 0
          logging_collector: "on"
          log_line_prefix:  "%m [%p]: [%l-1] user=%u,db=%d,client=%h "
          max_connections:  100
          max_parallel_workers: 2
          max_worker_processes: 2
          min_wal_size: "512MB"
          max_wal_size: "2048MB"
          password_encryption: "scram-sha-256"
          pgaudit.log: "role, ddl"
          pg_stat_statements.max: 10000
          shared_preload_libraries: 'pg_stat_statements'
          shared_buffers: 512MB
          superuser_reserved_connections: "6" 
          stats_temp_directory: 'pg_stat_tmp'
          track_activity_query_size: 4096
          track_activities: on
          track_counts: on
          track_io_timing: on
          track_wal_io_timing: on
          track_functions: none
          update_process_title: on
          work_mem: 4MB
