nameSuffix: -prod

secretGenerator:
- name: pg-s3-creds
  files:
  - s3.conf

generatorOptions:
  disableNameSuffixHash: true

bases:
  - ../../base/postgres

patchesStrategicMerge:
  - postgres.yaml


